### ISSUE TITLE
go get failed

### ISSUE THREAD

**Issue by forward32** [VKCOM/kittenhouse#5]
go1.12.1 linux/amd64

```go
# github.com/vkcom/kittenhouse/core/clickhouse
../../../../pkg/mod/github.com/vkcom/kittenhouse@v0.0.0-20190214191346-10ab71abae30/core/clickhouse/compress.go:22:91: cannot use 0 (type int) as type []int in argument to lz4.CompressBlock```

**Comment by YuriyNasretdinov** [comment]
It's still interesting why it didn't work for you though. Obviously it is related to the fact that lz4 package API changed in master, but that's what vendor/ directory is for, or at least I thought it is :).

I wasn't able to reproduce it.

```
> go version
go version go1.12 linux/amd64
> go get -v github.com/vkcom/kittenhouse
github.com/vkcom/kittenhouse (download)
github.com/valyala/fasthttp (download)
github.com/klauspost/compress (download)
github.com/klauspost/cpuid (download)       
github.com/valyala/bytebufferpool (download)
github.com/vkcom/engine-go (download)     
github.com/go-errors/errors (download)   
github.com/vkcom/kittenhouse       
# github.com/vkcom/kittenhouse
```

**Comment by forward32** [comment]
I got this error installing kittenhouse from root of my project which contains `go.mod/go.sum` with turned-on GO111MODULE. Fixed it, thanks.

Do you have any documentation or something to avoid watching the code each time I want understand something? Or maybe I can pm you via telegram/email?

Thanks!

**Comment by YuriyNasretdinov** [comment]
> Do you have any documentation or something to avoid watching the code each time I want understand something? Or maybe I can pm you via telegram/email?

I am actually not responsible for kittenhouse anymore :). So it's better to create issues, although I understand that it takes more time.

**Comment by forward32** [comment]
Got it, thanks for quick replies! :)
