### ISSUE TITLE
KittenHouse won't retry delivering data

### ISSUE THREAD

**Issue by dmftaras** [VKCOM/kittenhouse#7]
Hey,
I'm currently having an issues with the KittenHouse. Basically when CH goes down, data are being lost, and KittenHouse won't try to be delivered again.

Here's my KittenHouse log:
`
/root/go/bin/kittenhouse -u='' -g='' -ch-addr=<SERVER_IP>:8123
2019/05/23 07:24:11.193465 main.go:123: Updating config
2019/05/23 07:24:11.193597 conf.go:40: Asked to update config for persistent senders
2019/05/23 07:24:11.193615 conf.go:53: Stopping all persistent senders
2019/05/23 07:24:11.193625 conf.go:65: Persistent senders stopped
2019/05/23 07:24:11.193809 udp.go:71: Listening 0.0.0.0:13338 (UDP)
2019/05/23 07:24:11.193952 send.go:250: Starting persistent loop (servers = [<SERVER_IP>:8123], default = true, tables = [])
2019/05/23 07:29:20.444431 flush.go:473: Could not post to table email_log.sent_emails(uuid,event_time,store_id,status,is_marketing,trigger_type_id,model_trigger_id,model_target_id,seq_num,from_email,from_name,subject,to_email,to_name,mailgun_message_id,created_at,debug_trace_json,headers_json,html) to clickhouse: Post http://<SERVER_IP>:8123/?input_format_values_interpret_expressions=0&query=INSERT%20INTO%20email_log.sent_emails%28uuid%2Cevent_time%2Cstore_id%2Cstatus%2Cis_marketing%2Ctrigger_type_id%2Cmodel_trigger_id%2Cmodel_target_id%2Cseq_num%2Cfrom_email%2Cfrom_name%2Csubject%2Cto_email%2Cto_name%2Cmailgun_message_id%2Ccreated_at%2Cdebug_trace_json%2Cheaders_json%2Chtml%29%20VALUES: dial tcp <SERVER_IP>:8123: connect: connection refused
2019/05/23 07:29:20.444460 setting.go:99: Temporarily disabled <SERVER_IP>:8123
2019/05/23 07:29:21.246378 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:29:23.246675 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:29:25.246935 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:29:27.247283 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:29:29.247656 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:29:31.247966 send.go:303: Could not send file internal_logs_buffer_20190523_072411_943a7b4b.clk: No servers available
2019/05/23 07:30:09.628066 setting.go:115: Checking whether <SERVER_IP>:8123 is alive
2019/05/23 07:30:09.637427 setting.go:132: Server <SERVER_IP>:8123 is back alive
`

Please let me know if such cases are handled by KittenHouse at all, since in the project description it says that it supports "on-disk data buffering with retries support".
I suppose that I need to enable on-disk data buffering then, if so, how do I do that? Is it "persistent=1" in the query while sending data?

Thanks

**Comment by YuriyNasretdinov** [comment]
Hi, you need to use persistent=1 specified as a request parameter if you want data to be retried. It is a feature that by default it does not do that so that it is a conscious decision that you need to make for each type of data that you write.

**Comment by dmftaras** [comment]
@YuriyNasretdinov thanks for your help, that worked perfectly, and may I know what's the logic behind it? e.g. is there a limit of retries and what's the interval between the retries? Thanks

**Comment by YuriyNasretdinov** [comment]
There is no limit to a number of retries. The interval is dynamic and it depends on the number of failures that happened before.

**Comment by dmftaras** [comment]
awesome, thanks
